shared:
  image: node:12
  steps:
    - init: npm install -y nginx

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - who: whoami
      - greet: ls -al
  build:
    requires: [~pr, ~commit]
    steps:
      - init: npm install -y nginx
  publish:
    requires: main
    steps:
      - publish: echo published!
      - deploy: cp ./src/html/index.html /root/sd-in-a-box/nginx/html
