shared:
  image: node:12
  steps:
    - init: npm install
    - test: npm test

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - greet: echo hello
  publish:
    requires: main
    steps:
      - publish: echo publish
