shared:
  image: docker:latest
  steps:
    - init: dpcker --version

jobs:
  check:
    requires: [~pr, ~commit]
    steps:
      - who: whoami
      - list: ls -al
  build:
    requires: [~pr, ~commit]
    steps:
      - init: docker build -t screwdriver_registry_1:5000/tomita/myapp:latest ./src/app/
      - publish: docker push screwdriver_registry_1:5000/tomita/myapp:latest 
  # deploy:
  #   requires: build
  #   steps:
  #     - 